<!DOCTYPE html>
{{-- F-10 — Clubbed Invoice PDF template.
     Layout follows SRS §2.19.3:
       • Header block (client/period/no-of-samples/online-password/generated-by)
       • Billing summary grouped by Test Category + Rate (one row per category)
       • Calculation row showing transparent formula
       • Charges block + Authorized Signatory + Barcode (encodes clubbed_slug) --}}
<html lang="en">
<head>
<meta charset="utf-8">
<style>
  body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111; }
  h2 { margin: 0 0 4px; font-size: 16px; color: #1e3a8a; }
  .meta-table { width: 100%; border-collapse: collapse; margin: 10px 0; }
  .meta-table td { border: 1px solid #ccc; padding: 5px 7px; vertical-align: top; }
  .meta-table td.label { background: #f3f4f6; font-weight: 600; width: 22%; }
  .billing { width: 100%; border-collapse: collapse; margin-top: 10px; }
  .billing th, .billing td { border: 1px solid #ccc; padding: 5px 7px; }
  .billing th { background: #1e3a8a; color: white; text-align: left; }
  .billing td.num, .billing th.num { text-align: right; }
  .totals { width: 100%; margin-top: 8px; }
  .totals td { padding: 4px 7px; }
  .totals td.label { font-weight: 600; text-align: right; }
  .totals td.value { text-align: right; width: 25%; }
  .formula { font-style: italic; color: #475569; margin-top: 6px; }
  .footer { margin-top: 24px; display: flex; justify-content: space-between; }
  .signatory { width: 40%; border-top: 1px solid #333; padding-top: 4px; font-size: 11px; }
  .disclaimer { font-size: 9px; color: #64748b; margin-top: 18px; }
  .barcode-area { text-align: right; font-family: "Libre Barcode 128", monospace; font-size: 28px; }
  .barcode-fallback { font-family: monospace; letter-spacing: 1px; font-size: 10px; }
</style>
</head>
<body>

<table style="width:100%; border:none;">
  <tr>
    <td style="border:none; vertical-align: top;">
      <h2>{{ $waterSampleInvoice->waterSample?->laboratory?->name ?? 'PHED Water Quality Lab' }}</h2>
      <div>Clubbed Invoice</div>
    </td>
    <td style="border:none; text-align: right; vertical-align: top;">
      <div><strong>No:</strong> {{ $waterSampleInvoice->clubbed_slug }}</div>
      <div><strong>Date:</strong> {{ optional($waterSampleInvoice->created_at)->format('d M Y') }}</div>
    </td>
  </tr>
</table>

<table class="meta-table">
  <tr>
    <td class="label">Client Name</td>
    <td>{{ $client?->name ?? $client?->organization_name ?? '—' }}</td>
    <td class="label">No. of Samples</td>
    <td>{{ $childCount }}</td>
  </tr>
  <tr>
    <td class="label">Address / District</td>
    <td>{{ $client?->address ?? '—' }}</td>
    <td class="label">Period Covered</td>
    <td>
      {{ optional($waterSampleInvoice->period_from)->format('d M Y') ?? '—' }}
      &nbsp;–&nbsp;
      {{ optional($waterSampleInvoice->period_to)->format('d M Y') ?? '—' }}
    </td>
  </tr>
  <tr>
    <td class="label">Client Detail</td>
    <td>{{ $client?->phone ?? '—' }} {{ $client?->email ? '· ' . $client->email : '' }}</td>
    <td class="label">Generated By</td>
    <td>{{ $waterSampleInvoice->createdByUser?->name ?? 'System' }}</td>
  </tr>
  <tr>
    <td class="label">Online Viewing (Password)</td>
    <td colspan="3"><strong>{{ $waterSampleInvoice->online_viewing_password ?? '—' }}</strong> &nbsp;<em>(use on client portal)</em></td>
  </tr>
</table>

<div style="margin-top: 10px; font-weight: 600; color: #1e3a8a;">Billing Summary (grouped by test category &amp; rate):</div>
<table class="billing">
  <thead>
    <tr>
      <th>S#</th>
      <th>Test Category / Description</th>
      <th>Receipt IDs</th>
      <th class="num">No. of Samples</th>
      <th class="num">Rate / Sample (PKR)</th>
      <th class="num">Amount (PKR)</th>
    </tr>
  </thead>
  <tbody>
    @php $idx = 1; @endphp
    @foreach($billingSummary['items'] as $cat => $row)
      <tr>
        <td>{{ $idx++ }}</td>
        <td><strong>{{ $cat }}</strong></td>
        <td>{{ implode(', ', $row['receipt_ids'] ?? []) }}</td>
        <td class="num">{{ $row['count'] }}</td>
        <td class="num">{{ number_format((float) $row['rate']) }}</td>
        <td class="num">{{ number_format($row['count'] * (float) $row['rate']) }}</td>
      </tr>
    @endforeach
  </tbody>
</table>

<div class="formula">{{ $billingSummary['formula'] }}</div>

<table class="totals">
  <tr>
    <td class="label">Service Charges:</td>
    <td class="value">PKR 0</td>
  </tr>
  <tr>
    <td class="label">Analysis Charges:</td>
    <td class="value">PKR {{ number_format((float) $waterSampleInvoice->net_amount) }}</td>
  </tr>
  <tr>
    <td class="label" style="border-top: 1px solid #333;">Total Charges:</td>
    <td class="value" style="border-top: 1px solid #333;"><strong>PKR {{ number_format((float) $waterSampleInvoice->net_amount) }}</strong></td>
  </tr>
</table>

<div class="footer">
  <div class="signatory">Authorized Signatory &amp; Stamp</div>
  <div class="barcode-area">
    {{-- Libre Barcode 128 needs the font installed in wkhtmltopdf. We also
         emit the raw slug so scanners and the human eye both work. --}}
    *{{ $waterSampleInvoice->clubbed_slug }}*
    <div class="barcode-fallback">{{ $waterSampleInvoice->clubbed_slug }}</div>
  </div>
</div>

<div class="disclaimer">
  The constituent individual receipts listed above are locked to this clubbed invoice
  and cannot be re-included in any future clubbed invoice. Any payment recorded
  against this clubbed invoice is proportionally credited to the underlying receipts.
</div>

</body>
</html>
