<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Role;

class AssignRolePermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        try {
            DB::beginTransaction();
            $systemAdministrator = Role::query()
                ->where('name', 'system-administrator')
                ->first();

            $permissions = [
                'add_assets',
                'edit_assets',
                'show_assets',
                'view_assets',
                'delete_assets',
                'add_asset_logs',
                'edit_asset_logs',
                'add_asset_maintenance_logs',
                'add_asset_maintenance_schedules',
                'edit_asset_maintenance_schedules',
                'show_asset_maintenance_schedules',
                'view_asset_maintenance_schedules',
                'delete_asset_maintenance_schedules',
                'add_material',
                'edit_material',
                'show_material',
                'view_material',
                'delete_material',
                'add_material_logs',
                'add_issues',
                'edit_issues',
                'show_issues',
                'view_issues',
                'delete_issues',
                'add_issue_logs',
                'add_issuable',
                'add_issue_responsible',
                'edit_issue_responsible',
                'delete_issue_responsible',
                'view_issue_responsible',
//                'add_complaints',
//                'edit_complaints',
                'show_complaints',
                'view_complaints',
//                'delete_complaints',
                'add_complaint_logs',
                'edit_complaint_logs',
                'edit_complaint_status',
                'add_complaint_types',
                'view_complaint_types',
                'delete_complaint_types',
                'add_laboratories',
                'edit_laboratories',
                'show_laboratories',
                'view_laboratories',
                'delete_laboratories',
                'add_laboratory_users',
                'delete_laboratory_users',
                'add_tests',
                'edit_tests',
                'show_tests',
                'view_tests',
                'delete_tests',
                'add_water_schemes',
//                'edit_water_schemes',
                'show_water_schemes',
                'view_water_schemes',
                'delete_water_schemes',
                'add_provinces',
                'edit_provinces',
                'show_provinces',
                'view_provinces',
                'delete_provinces',
                'add_divisions',
                'edit_divisions',
                'show_divisions',
                'view_divisions',
                'delete_divisions',
                'add_districts',
                'edit_districts',
                'show_districts',
                'view_districts',
                'delete_districts',
                'add_tehsils',
                'edit_tehsils',
                'show_tehsils',
                'view_tehsils',
                'delete_tehsils',
                'add_union_councils',
                'edit_union_councils',
                'show_union_councils',
                'view_union_councils',
                'delete_union_councils',
                'add_water_samples',
                'edit_water_samples',
                'show_water_samples',
                'view_water_samples',
//                'delete_water_samples',
//                'add_water_sample_details',
//                'edit_water_sample_details',
                'show_water_sample_details',
//                'delete_water_sample_details',
//                'edit_test_report',
                'show_test_report',
                'edit_water_sample_results',
//                'edit_water_sample_invoices',
                'show_water_sample_invoices',
                'add_water_sample_sop',
                'show_water_sample_sop',
                'view_sample_analysis',
                'add_abbreviations',
                'edit_abbreviations',
                'show_abbreviations',
                'view_abbreviations',
                'delete_abbreviations',
                'add_settings',
                'edit_settings',
                'view_settings',
                'add_invoices',
                'edit_invoices',
                'show_invoices',
                'view_invoices',
                'delete_invoices',
//                'add_inventories',
//                'edit_inventories',
                'show_inventories',
                'view_inventories',
//                'delete_inventories',
                'show_inventory_details',
//                'edit_inventory_details',
//                'delete_inventory_details',
                'show_inventory_logs',
                'edit_inventory_approve_status',
                'edit_inventory_issue_status',
//                'add_payments',
//                'edit_payments',
                'show_payments',
                'view_payments',
//                'delete_payments',
                'add_purchase_orders',
                'edit_purchase_orders',
                'show_purchase_orders',
                'view_purchase_orders',
                'delete_purchase_orders',
                'edit_purchase_order_status',
                'add_term_and_conditions',
                'edit_term_and_conditions',
                'show_term_and_conditions',
                'view_term_and_conditions',
                'delete_term_and_conditions',
                'add_users',
                'edit_users',
                'show_users',
                'view_users',
                'delete_users',
//                'add_clients',
//                'edit_clients',
                'show_clients',
                'view_clients',
                'delete_clients',
                'add_designations',
                'edit_designations',
                'show_designations',
                'view_designations',
                'delete_designations',
                'add_roles',
                'edit_roles',
                'show_roles',
                'view_roles',
                'delete_roles',
                'add_role_permissions',
                'show_role_has_permissions',
//                'add_permissions',
                'add_units',
                'edit_units',
                'show_units',
                'view_units',
                'delete_units',
                'water_quality_analysis_report',
                'laboratory_analysis_report',
                'central_water_analysis_report',
                'view_reports',
                'show_handing_takings',
                'view_handing_takings',
                'show_folders',
                'view_folders',
                'show_diaries',
                'view_diaries',
                'show_dispatches',
                'view_dispatches',
            ];
            $systemAdministrator->syncPermissions($permissions);

            $systemManager = Role::query()
                ->where('name', 'system-manager')
                ->first();

            $permissions = [
                'add_tests',
                'edit_tests',
                'show_tests',
                'view_tests',
                'delete_tests',
                'add_water_samples',
                'edit_water_samples',
                'show_water_samples',
                'view_water_samples',
                'delete_water_samples',
                'add_water_sample_details',
                'edit_water_sample_details',
                'show_water_sample_details',
                'delete_water_sample_details',
                'edit_water_sample_invoices',
                'edit_test_report',
                'show_test_report',
                'edit_water_sample_results',
                'show_water_sample_invoices',
                'show_water_sample_sop',
                'view_sample_analysis',
                'add_asset_logs',
                'edit_asset_logs',
                'add_asset_maintenance_logs',
                'add_asset_maintenance_schedules',
                'edit_asset_maintenance_schedules',
                'show_asset_maintenance_schedules',
                'view_asset_maintenance_schedules',
                'delete_asset_maintenance_schedules',
                'add_issues',
                'edit_issues',
                'show_issues',
                'view_issues',
                'delete_issues',
                'add_issuable',
                'add_complaints',
                'edit_complaints',
                'show_complaints',
                'view_complaints',
                'delete_complaints',
                'add_complaint_logs',
                'edit_complaint_logs',
                'edit_complaint_status',
                'add_complaint_types',
                'view_complaint_types',
                'delete_complaint_types',
                'add_laboratories',
                'edit_laboratories',
                'show_laboratories',
                'view_laboratories',
                'delete_laboratories',
                'view_laboratory_assets',
                'view_laboratory_material',
                'add_users',
                'edit_users',
                'show_users',
                'view_users',
                'delete_users',
                'add_laboratory_users',
                'delete_laboratory_users',
                'add_water_schemes',
//                'edit_water_schemes',
                'show_water_schemes',
                'view_water_schemes',
                'add_inventories',
                'edit_inventories',
                'show_inventories',
                'view_inventories',
                'delete_inventories',
                'inventory_received',
                'show_inventory_details',
                'edit_inventory_details',
                'delete_inventory_details',
                'show_inventory_logs',
                'add_handing_takings',
                'edit_handing_takings',
                'show_handing_takings',
                'view_handing_takings',
                'delete_handing_takings',
                'show_water_sample_sop',
                'add_payments',
                'edit_payments',
                'show_payments',
                'view_payments',
                'delete_payments',
                'show_clients',
                'view_clients',
                'view_roles',
                'show_folders',
                'add_folders',
                'edit_folders',
                'delete_folders',
                'view_folders',
                'add_diaries',
                'edit_diaries',
                'show_diaries',
                'view_diaries',
                'delete_diaries',
                'add_dispatches',
                'edit_dispatches',
                'show_dispatches',
                'view_dispatches',
                'delete_dispatches',
            ];

            $systemManager->syncPermissions($permissions);

            $juniorClerk = Role::query()
                ->where('name', 'junior-clerk')
                ->first();

            // SRS §1.2 role split:
            //   junior-clerk         → sample REGISTRATION + diary/dispatch
            //   laboratory-assistant → ANALYSIS (test execution + result entry)
            //
            // Analysis-side perms (add/edit/delete water_sample_details,
            // edit_water_sample_results, edit_test_report) are deliberately
            // omitted here so the Analysis Entry menu / endpoints stay hidden
            // from clerks. Read-side (show_water_sample_details, show_test_report,
            // view_sample_analysis) is kept so clerks can see status / results
            // for samples they registered.
            $permissions = [
                'add_tests',
                'edit_tests',
                'show_tests',
                'view_tests',
                'delete_tests',
                'add_water_samples',
                'edit_water_samples',
                'show_water_samples',
                'view_water_samples',
                'delete_water_samples',
                'show_water_sample_details',
                'edit_water_sample_invoices',
                'show_test_report',
                'show_water_sample_invoices',
                'show_water_sample_sop',
                'view_sample_analysis',
                'add_water_schemes',
//                'edit_water_schemes',
                'view_water_schemes',
                'show_water_schemes',
                'add_issues',
                'edit_issues',
                'show_issues',
                'view_issues',
                'delete_issues',
                'add_complaints',
                'edit_complaints',
                'show_complaints',
                'view_complaints',
                'delete_complaints',
                'add_complaint_logs',
                'edit_complaint_logs',
                'add_payments',
                'edit_payments',
                'show_payments',
                'view_payments',
                'delete_payments',
                'show_clients',
                'view_clients',
            ];

            $juniorClerk->syncPermissions($permissions);

            $laboratoryAssistant = Role::query()
                ->where('name', 'laboratory-assistant')
                ->first();

//            $permissions = [
//                'add_water_samples',
//                'edit_water_samples',
//                'show_water_samples',
//                'view_water_samples',
//                'delete_water_samples',
//                'view_water_schemes',
//                'add_water_schemes',
//                'show_water_schemes',
//                'add_issues',
//                'edit_issues',
//                'show_issues',
//                'view_issues',
//                'delete_issues',
//                'add_complaints',
//                'edit_complaints',
//                'show_complaints',
//                'view_complaints',
//                'delete_complaints',
//                'add_complaint_logs',
//                'edit_complaint_logs',
//                'show_water_sample_sop',
//                'view_sample_analysis'
//            ];

            $laboratoryAssistant->syncPermissions($permissions);


            DB::commit();
        } catch (\Exception $exception) {
            info($exception->getMessage());
            DB::rollBack();
        }

    }
}
