<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            [
                'module_id' => 1,
                'name' => 'add_assets',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'edit_assets',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'show_assets',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'view_assets',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'delete_assets',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'add_asset_logs',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'edit_asset_logs',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'add_asset_maintenance_logs',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'add_asset_maintenance_schedules',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'edit_asset_maintenance_schedules',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'show_asset_maintenance_schedules',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'view_asset_maintenance_schedules',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'delete_asset_maintenance_schedules',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'view_laboratory_assets',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'add_material',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'edit_material',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'show_material',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'view_material',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'delete_material',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 2,
                'name' => 'add_material_logs',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 1,
                'name' => 'view_laboratory_material',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'add_issues',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'edit_issues',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'show_issues',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'view_issues',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'delete_issues',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'add_issue_logs',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'add_issuable',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'add_issue_responsible',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'edit_issue_responsible',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'view_issue_responsible',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 3,
                'name' => 'delete_issue_responsible',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'add_complaints',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'edit_complaints',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'show_complaints',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'view_complaints',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'delete_complaints',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'add_complaint_logs',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'edit_complaint_logs',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'edit_complaint_status',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'add_complaint_types',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'view_complaint_types',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 4,
                'name' => 'delete_complaint_types',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'add_laboratories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'edit_laboratories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'show_laboratories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'view_laboratories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'delete_laboratories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'add_laboratory_users',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 5,
                'name' => 'delete_laboratory_users',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'add_tests',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'edit_tests',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'show_tests',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'view_tests',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 6,
                'name' => 'delete_tests',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'add_water_schemes',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'edit_water_schemes',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'show_water_schemes',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'view_water_schemes',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 7,
                'name' => 'delete_water_schemes',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'add_provinces',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'edit_provinces',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'show_provinces',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'view_provinces',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 8,
                'name' => 'delete_provinces',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'add_divisions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'edit_divisions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'show_divisions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'view_divisions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 9,
                'name' => 'delete_divisions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'add_districts',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'edit_districts',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'show_districts',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'view_districts',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 10,
                'name' => 'delete_districts',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 11,
                'name' => 'add_tehsils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 11,
                'name' => 'edit_tehsils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 11,
                'name' => 'show_tehsils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 11,
                'name' => 'view_tehsils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 11,
                'name' => 'delete_tehsils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 12,
                'name' => 'add_union_councils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 12,
                'name' => 'edit_union_councils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 12,
                'name' => 'show_union_councils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 12,
                'name' => 'view_union_councils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 12,
                'name' => 'delete_union_councils',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'add_water_samples',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'edit_water_samples',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'show_water_samples',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'view_water_samples',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'delete_water_samples',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'add_water_sample_details',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'edit_water_sample_details',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'show_water_sample_details',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'delete_water_sample_details',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'edit_test_report',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'show_test_report',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'edit_water_sample_results',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'edit_water_sample_invoices',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'show_water_sample_invoices',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'add_water_sample_sop',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'show_water_sample_sop',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 13,
                'name' => 'view_sample_analysis',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 14,
                'name' => 'add_abbreviations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 14,
                'name' => 'edit_abbreviations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 14,
                'name' => 'show_abbreviations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 14,
                'name' => 'view_abbreviations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 14,
                'name' => 'delete_abbreviations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 15,
                'name' => 'add_settings',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 15,
                'name' => 'edit_settings',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 15,
                'name' => 'view_settings',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 16,
                'name' => 'add_invoices',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 16,
                'name' => 'edit_invoices',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 16,
                'name' => 'show_invoices',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 16,
                'name' => 'view_invoices',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 16,
                'name' => 'delete_invoices',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'add_inventories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'edit_inventories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'show_inventories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'view_inventories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'inventory_received',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'delete_inventories',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'show_inventory_details',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'edit_inventory_details',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'delete_inventory_details',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'show_inventory_logs',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'edit_inventory_approve_status',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 17,
                'name' => 'edit_inventory_issue_status',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 18,
                'name' => 'add_payments',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 18,
                'name' => 'edit_payments',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 18,
                'name' => 'show_payments',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 18,
                'name' => 'view_payments',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 18,
                'name' => 'delete_payments',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 19,
                'name' => 'add_purchase_orders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 19,
                'name' => 'edit_purchase_orders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 19,
                'name' => 'show_purchase_orders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 19,
                'name' => 'view_purchase_orders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 19,
                'name' => 'delete_purchase_orders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 19,
                'name' => 'edit_purchase_order_status',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 20,
                'name' => 'add_term_and_conditions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 20,
                'name' => 'edit_term_and_conditions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 20,
                'name' => 'show_term_and_conditions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 20,
                'name' => 'view_term_and_conditions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 20,
                'name' => 'delete_term_and_conditions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 21,
                'name' => 'add_users',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 21,
                'name' => 'edit_users',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 21,
                'name' => 'show_users',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 21,
                'name' => 'view_users',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 21,
                'name' => 'delete_users',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 21,
                'name' => 'hr_list',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 22,
                'name' => 'add_clients',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 22,
                'name' => 'edit_clients',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 22,
                'name' => 'show_clients',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 22,
                'name' => 'view_clients',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 22,
                'name' => 'delete_clients',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 23,
                'name' => 'add_designations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 23,
                'name' => 'edit_designations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 23,
                'name' => 'show_designations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 23,
                'name' => 'view_designations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 23,
                'name' => 'delete_designations',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 24,
                'name' => 'add_roles',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 24,
                'name' => 'edit_roles',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 24,
                'name' => 'show_roles',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 24,
                'name' => 'view_roles',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 24,
                'name' => 'delete_roles',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 24,
                'name' => 'add_role_permissions',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 24,
                'name' => 'show_role_has_permissions',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 25,
                'name' => 'add_permissions',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 26,
                'name' => 'add_units',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 26,
                'name' => 'edit_units',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 26,
                'name' => 'show_units',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 26,
                'name' => 'view_units',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 26,
                'name' => 'delete_units',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 27,
                'name' => 'add_handing_takings',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 27,
                'name' => 'edit_handing_takings',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 27,
                'name' => 'show_handing_takings',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 27,
                'name' => 'view_handing_takings',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 27,
                'name' => 'delete_handing_takings',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 28,
                'name' => 'water_quality_analysis_report',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 28,
                'name' => 'laboratory_analysis_report',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 28,
                'name' => 'central_water_analysis_report',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 28,
                'name' => 'view_reports',
                'guard_name' => 'web',
                'is_custom' => true,
                'created_at' => now(),
            ],
            [
                'module_id' => 29,
                'name' => 'add_folders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 29,
                'name' => 'edit_folders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 29,
                'name' => 'show_folders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 29,
                'name' => 'view_folders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 29,
                'name' => 'delete_folders',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 30,
                'name' => 'add_diaries',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 30,
                'name' => 'edit_diaries',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 30,
                'name' => 'show_diaries',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 30,
                'name' => 'view_diaries',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 30,
                'name' => 'delete_diaries',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 31,
                'name' => 'add_dispatches',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 31,
                'name' => 'edit_dispatches',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 31,
                'name' => 'show_dispatches',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 31,
                'name' => 'view_dispatches',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
            [
                'module_id' => 31,
                'name' => 'delete_dispatches',
                'guard_name' => 'web',
                'is_custom' => false,
                'created_at' => now(),
            ],
        ];

        if (0 === Permission::query()->count()) {
            Permission::query()->insert($permissions);
        }
    }
}
