<?php

namespace Database\Seeders;

use App\Enums\OnDemandTestEnum;
use App\Enums\TestTypeEnum;
use App\Models\Test;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class TestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tests = [
            [
                'type' => TestTypeEnum::PHYSICAL,
                'water_quality_parameter' => "Color",
                'unit' => "-",
                'detectable_limit' => "-",
                'reference_method' => "Sensory evaluation",
                'permissible_limits' => "Clear/Colorless",
                'is_mandatory' => true,
                'rate' => 0,

            ],
            [
                'type' => TestTypeEnum::PHYSICAL,
                'water_quality_parameter' => "Odor",
                'unit' => "-",
                'detectable_limit' => "-",
                'reference_method' => "Sensory evaluation",
                'permissible_limits' => "Unobjectionable (U.O)",
                'is_mandatory' => true,
                'rate' => 0,
            ],
            [
                'type' => TestTypeEnum::PHYSICAL,
                'water_quality_parameter' => "Taste",
                'unit' => "-",
                'detectable_limit' => "-",
                'reference_method' => "Sensory evaluation",
                'permissible_limits' => "Unobjectionable (U.O)",
                'is_mandatory' => true,
                'rate' => 0,
            ],
            [
                'type' => TestTypeEnum::PHYSICAL,
                'water_quality_parameter' => "pH",
                'unit' => "-",
                'detectable_limit' => "0.02",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "6.5-8.5 (WHO, 2004)",
                'is_mandatory' => true,
                'rate' => 50,
            ],
            [
                'type' => TestTypeEnum::PHYSICAL,
                'water_quality_parameter' => "E.C",
                'unit' => "µS/cm",
                'detectable_limit' => "0.2875",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "NGVS",
                'is_mandatory' => true,
                'rate' => 50,
            ],
            [
                'type' => TestTypeEnum::PHYSICAL,
                'water_quality_parameter' => "Turbidity",
                'unit' => "FNU",
                'detectable_limit' => "6.8",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "5 (WHO 2004)",
                'is_mandatory' => true,
                'rate' => 100,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "TDS",
                'unit' => "mg/L",
                'detectable_limit' => "-",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "1000 (WHO 2004)",
                'is_mandatory' => true,
                'rate' => 50,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Hardness",
                'unit' => "mg/L",
                'detectable_limit' => "5",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "500 (WHO, 2004)",
                'is_mandatory' => true,
                'rate' => 150,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Calcium",
                'unit' => "mg/L",
                'detectable_limit' => "2",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "200 (WHO, 2004)",
                'is_mandatory' => true,
                'rate' => 100,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Magnesium",
                'unit' => "mg/L",
                'detectable_limit' => "1",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "150 (WHO, 2004)",
                'is_mandatory' => true,
                'rate' => 100,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Alkalinity",
                'unit' => "mg/L",
                'detectable_limit' => "-",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "NGVS",
                'is_mandatory' => true,
                'rate' => 100,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "T-Alkalinity",
                'unit' => "mg/L",
                'detectable_limit' => "-",
                'reference_method' => "-",
                'permissible_limits' => "-",
                'is_mandatory' => true,
                'rate' => '-',
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "P-Alkalinity",
                'unit' => "mg/L",
                'detectable_limit' => "-",
                'reference_method' => "-",
                'permissible_limits' => "-",
                'is_mandatory' => true,
                'rate' => '-',
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "OH-Alkalinity",
                'unit' => "mg/L",
                'detectable_limit' => "-",
                'reference_method' => "-",
                'permissible_limits' => "-",
                'is_mandatory' => true,
                'rate' => '-',
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Carbonate",
                'unit' => "mg/L",
                'detectable_limit' => "5",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "NGVS",
                'is_mandatory' => true,
                'rate' => 100,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Bicarbonate",
                'unit' => "mg/L",
                'detectable_limit' => "5",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "NGVS",
                'is_mandatory' => true,
                'rate' => 100,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Chloride",
                'unit' => "mg/L",
                'detectable_limit' => "2",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "250 (WHO, 2004)",
                'is_mandatory' => true,
                'rate' =>100 ,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Sodium",
                'unit' => "mg/L",
                'detectable_limit' => "1",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "200 (NSDWQ 2008)",
                'is_mandatory' => true,
                'rate' => 150,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Nitrate",
                'unit' => "mg/L",
                'detectable_limit' => "0.06",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "10 (WHO, 2004)",
                'is_mandatory' => true,
                'rate' => 150,
            ],
            [
                'type' => TestTypeEnum::CHEMICAL,
                'water_quality_parameter' => "Sulphate",
                'unit' => "mg/L",
                'detectable_limit' => "0.04",
                'reference_method' => "APHA, 20th Edition",
                'permissible_limits' => "250 (WHO, 2004)",
                'is_mandatory' => true,
                'rate' => 150,
            ],
            [
                'type' => TestTypeEnum::Microbiological_Kit,
                'water_quality_parameter' => "Total Coliform",
                'unit' => null,
                'detectable_limit' => "1 CFU/1 ml",
                'reference_method' => "Petrifilm",
                'permissible_limits' => "0 CFU/1 ml",
                'is_mandatory' => true,
                'rate' => 1000,
            ],
            [
                'type' => TestTypeEnum::Microbiological_Kit,
                'water_quality_parameter' => "Fecal Colifrom",
                'unit' => null,
                'detectable_limit' => "1 CFU/1 ml",
                'reference_method' => "Petrifilm",
                'permissible_limits' => "0 CFU/1 ml",
                'is_mandatory' => true,
                'rate' => 1000,
            ],
            [
                'type' => TestTypeEnum::Microbiological_Kit,
                'water_quality_parameter' => "Total Coliform",
                'unit' => null,
                'detectable_limit' => "+Ve/-Ve",
                'reference_method' => "KIT-Method",
                'permissible_limits' => "-Ve",
                'is_mandatory' => true,
                'rate' => 500,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Arsenic',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 500,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Fluoride',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 200,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Iron',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 300,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Mercury',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 0,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Aluminum',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 500,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Ammonia',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 200,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Chromium',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 500,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Copper',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 500,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Cyanide',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 500,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Iodine',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 200,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Manganese',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 500,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Molybdenum',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 500,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Nickle',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 200,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Phosphorus',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 200,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Total Chlorine',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 100,
            ],
            [
                'type' => TestTypeEnum::ON_DEMAND,
                'water_quality_parameter' => 'Free Chlorine',
                'unit' => null,
                'detectable_limit' => "N/A",
                'reference_method' => "N/A",
                'permissible_limits' => "N/A",
                'is_mandatory' => false,
                'rate' => 100,
            ],
        ];

        try {
            DB::beginTransaction();
            Test::query()->insert($tests);
            DB::commit();
        } catch (\Exception $exception) {
            Log::error($exception->getMessage());
            DB::rollBack();
        }
    }
}
