<?php

namespace Database\Seeders;

use App\Models\Tehsil;
use App\Models\UnionCouncil;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnionCouncilSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $unionCouncils = [
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Azim Shah'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Bgho Bahar'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Chachran Sharif'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Chak No.45/p'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Chandia.'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Dinpur Sharif'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Ghari Iftikhar Khan'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Ghazipur'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Ghena Lar (h.q.jangi)'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Islam Garh'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Jajja Abbasian'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Jetha Bhutta'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Jhoran'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Kotla Pathan'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Latki'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Mari Allah Bachaya'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Mud Bhoora'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Mueenabad'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Nawan Kot'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Neel Garh'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Qadirpur.'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Sehja'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'U.C.D Khan Pur'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'U.C-A Khan Pur'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'U.C-B Khan Pur'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'U.C-C Khan Pur'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'U.C-E Khan Pur'],
            ['tehsil_name' => 'Khanpur', 'uc_name' => 'Zahir Pir'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Agra'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Behlola'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Chindro Dag.'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Dargai'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Dheri Zardad'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Dosehra'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Ghunda Karkana'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Hassan Zai'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Hissara Yasinzai'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Khan Mahi'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Maira Umderzai'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Mera Parang'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Muhammad Nari'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Nisatta'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Rajjar-II'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Rajjar-II'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Sarki Titara'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Sheikho'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Tarnab'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'Turangzai'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'M.C. Charsadda-I'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'M.C. Charsadda-II'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'M.C. Charsadda-III'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'M.C. Charsadda-IV'],
            ['tehsil_name' => 'Charsadda', 'uc_name' => 'M.C. Umderzai'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Daulat Pura'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Hajizai'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Hassan Zai'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Kangra'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Katozai'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Matta Mughal Khel'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Shabqadar-I'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Shabqadar-II'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Shabqadar-III'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Panjpao'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Rashakai'],
            ['tehsil_name' => 'Shabqadar', 'uc_name' => 'Battagram'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Abazai'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Dhakki'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Gandhera'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Harichand'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Hisara Nehri'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Koz Behram Dheri'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Mandani'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'm.c. Tangi'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Mirzadher'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Sherpao'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Shodag'],
            ['tehsil_name' => 'Tangi', 'uc_name' => 'Zaim'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Alo'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Babini'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Babuzai'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Baghdada'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Bagh-e-Iram'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Baghicha Dheri'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Bakhshali'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Bala Garhi'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Bari Cham'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Bazar'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Bickut Gunj'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Chamtar'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Chargulli'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Chek Hoti'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Dagai'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Dheri'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Fatma'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Garhi Dulatzai'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Garhi Ismailzai'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Garyala'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Ghala Dher'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Gujar Garhi'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Gujrat'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Guli Bagh'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Gumbat'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Hoti'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Jamal Gharhi'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Kandar'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Kas'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Katakhat'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Kati Garhi'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Katlang-1'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Katlang-2'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Kharki'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Khazana Dheri'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Kohi'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Koroona'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Kot Dulatzai'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Machai'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Mangah'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Mardan Cantt'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Mardan Khass'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Mayar'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Mohib Banda'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Muhabbat Abad'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Muslim Abad'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Palo Dheri'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Par Hoti'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Qasmi'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Rorya'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Rural Mardan'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Rustam'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Sawaldher'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Shahbaz Garhi'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Shamatpur'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Shamozia'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Sikndari Purdil Abad'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Toru'],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Bijli Ghar '],
            ['tehsil_name' => 'Mardan', 'uc_name' => 'Maho Dheri'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Daman-e-koh'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Hatyan'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Jalala'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Jehangir Abad'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Kot Jungarah'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Lund Khwar'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Madey Baba'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Mokori'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Mian Essa'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Narai'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Parkho Dheri'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Patt Baba'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Pir Saddi'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Saro Shah'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Seri Behlol'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Sher Garh'],
            ['tehsil_name' => 'Takht Bhai', 'uc_name' => 'Takar'],
            ['tehsil_name' => 'Paroa', 'uc_name' => 'Lunda Sharif'],
            ['tehsil_name' => 'Paroa', 'uc_name' => 'Mahra'],
            ['tehsil_name' => 'Paroa', 'uc_name' => 'Malana'],
            ['tehsil_name' => 'Paroa', 'uc_name' => 'Miran'],
            ['tehsil_name' => 'Paroa', 'uc_name' => 'Naivela'],
            ['tehsil_name' => 'Paroa', 'uc_name' => 'Paroa'],
            ['tehsil_name' => 'Paroa', 'uc_name' => 'Kirri Shamozai'],
            ['tehsil_name' => 'Kulachi', 'uc_name' => 'Hathala'],
            ['tehsil_name' => 'Kulachi', 'uc_name' => 'Looni'],
            ['tehsil_name' => 'Kulachi', 'uc_name' => 'Maddi'],
            ['tehsil_name' => 'Kulachi', 'uc_name' => 'Urban U.C. Kulachi Town'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Abba Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Abdul Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Ahmed Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Bakhmal Ahmedzai'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Begu Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Behram Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Dara Tang'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Darra Pezu'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Daulat Tajazai'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Darkha Sulman Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Ghazni Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Issak Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Kaka Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Kharu Khel Pacca'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Urban U.C.NO.1 Lakki'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Urban U.C.NO.2 Lakki'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Landiwa'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Mash Masti Khani'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Masha Mansoor'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Mela Shahab Khel'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Pahar Khel Thal'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Samandi'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Tajori'],
            ['tehsil_name' => 'Lakki Marwat', 'uc_name' => 'Titar Khel Guli Jan'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Amandi'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Aral Hathi Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Asperka Waziran'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Baka Khel Wazir'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Barat'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Bannu Cantt'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Bazar Ahmed Khan'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Bizenkhel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Urban U.C CITY-1'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Urban U.C CITY-II'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Daud Shah'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Domel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Fatima Khel Kalan'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Garhi Sher Ahmed'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Ghoriwala'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Hassani'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Havid Landi Dak'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Hind Khel Wazir'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Hinjal'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Ismail Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Jani Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Jhando Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Kakki-I'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Kakki-II'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Kala Khel Masti Khan'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Kausar Fateh Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Khandar Khan Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Kawajamad'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Khojari'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Kot Qalandar'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Koti Saddat'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Lalozai'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Mama Khel Banoochi'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Mamash Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Mandan'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Mandev'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Mita Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Mira Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Muhammad Khel Wazir'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Mumbati Barakzai'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Nar Jaffar Khan'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Nezam Dherma Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Nurar'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Salima Sikaner Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Shahbaz Azmat Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Shamshi Khel'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Sikandar Khel Bala'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Sokri Karim Khan'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Sulima Sikander'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Takhti Khel Wazir'],
            ['tehsil_name' => 'Bannu', 'uc_name' => 'Zeraki Pirba Khel'],
            ['tehsil_name' => 'Banda Daud Shah', 'uc_name' => 'Bahader Khel'],
            ['tehsil_name' => 'Banda Daud Shah', 'uc_name' => 'Gurguri'],
            ['tehsil_name' => 'Banda Daud Shah', 'uc_name' => 'Jatta Ismail Khel'],
            ['tehsil_name' => 'Banda Daud Shah', 'uc_name' => 'Nari Panoos'],
            ['tehsil_name' => 'Banda Daud Shah', 'uc_name' => 'Teri'],
            ['tehsil_name' => 'Karak', 'uc_name' => 'Ghundi Mera Khan Khel'],
            ['tehsil_name' => 'Karak', 'uc_name' => 'Isak Chountra'],
            ['tehsil_name' => 'Karak', 'uc_name' => 'Jandri'],
            ['tehsil_name' => 'Karak', 'uc_name' => 'Karak (northern)'],
            ['tehsil_name' => 'Karak', 'uc_name' => 'Karak (southern)'],
            ['tehsil_name' => 'Karak', 'uc_name' => 'Latambar'],
            ['tehsil_name' => 'Karak', 'uc_name' => 'Mitha Khel'],
            ['tehsil_name' => 'Karak', 'uc_name' => 'Paloosa Sar'],
            ['tehsil_name' => 'Karak', 'uc_name' => 'Sabir Abad'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Balyamina'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Darband'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Ganjiano Kali'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Kahi'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Kach'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Khan Barhi'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Kotki'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Muhammad Khawja'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Raisan'],
            ['tehsil_name' => 'Hangu ', 'uc_name' => 'Togh Serai'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Ali Zai'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Bahadur Kot'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Billitang'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Churlaki'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Dhoda'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Gumbat'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Jerma'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Kharmatu'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Khusal Garh'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Lachi Urban'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Muhammadzai'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Nasrat Khel'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Shah Pur'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Shakardara Urban'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Sher Kot'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Sur Gul'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Tough Bala-1'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Tough Bala-2'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Kohat Urban-1'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Kohat Urban-2'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Kohat Urban-3'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Kohat Urban-4'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Kohat Urban-5'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Kohat Urban-6/Tippi'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Usterzai'],
            ['tehsil_name' => 'Kohat', 'uc_name' => 'Zayarat Shekh Allahadad'],
            ['tehsil_name' => 'Lachi', 'uc_name' => 'Lachi Rural'],
            ['tehsil_name' => 'Lachi', 'uc_name' => 'Mandoori'],
            ['tehsil_name' => 'Lachi', 'uc_name' => 'Shakardara-1'],
            ['tehsil_name' => 'Lachi', 'uc_name' => 'Shakardara-2'],
            ['tehsil_name' => 'Lachi', 'uc_name' => 'Sudal'],
            ['tehsil_name' => 'Lachi', 'uc_name' => 'Sumari'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Anbar'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Beka'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Dobian'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Jalbi'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Jalsi'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Jehangira'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Khunda'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Lahore Gharbi'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Lahore Shirqi'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Manki'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Mathani Changan'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Sard China'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Sudhair'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Thordher'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Yaqoobi'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Yar Hussain (east)'],
            ['tehsil_name' => 'Lahor', 'uc_name' => 'Yar Hussain (west)'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Batakara'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Gabasni'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Gandaf'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Gani Chatra'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Kabgani'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Kalabat'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Kotha'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Maini'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Pabeni'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Topi East'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Topi West'],
            ['tehsil_name' => 'Topi', 'uc_name' => 'Zarobi'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Adina'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Asota'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Bachai'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Bam Khel'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Chak Noda'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Dagai.'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Gar Munara'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Ismaila'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Jhanda'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Kalu Khan'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Karnal Sher Killi'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Maniri Bala'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Maniri Payan'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Marghuz'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Naranji'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Panchpir'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Parmoli'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Saleem Khan'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Shahmansoor'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Sheikh Jana'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Shewa'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Swabi Khas'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Swabi Maniri'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Tarakai'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Thand Kohi'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Turlandi'],
            ['tehsil_name' => 'Swabi', 'uc_name' => 'Zaida'],
            ['tehsil_name' => 'Puran', 'uc_name' => 'Aloch'],
            ['tehsil_name' => 'Puran', 'uc_name' => 'Bar Puran'],
            ['tehsil_name' => 'Puran', 'uc_name' => 'Behlol Khel'],
            ['tehsil_name' => 'Puran', 'uc_name' => 'Benglai'],
            ['tehsil_name' => 'Puran', 'uc_name' => 'Chowga'],
            ['tehsil_name' => 'Puran', 'uc_name' => 'Ismail Khel'],
            ['tehsil_name' => 'Puran', 'uc_name' => 'Kamach Nusrat Khel'],
            ['tehsil_name' => 'Puran', 'uc_name' => 'Martung Khass'],
            ['tehsil_name' => 'Puran', 'uc_name' => 'Musa Khel'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Alpuri'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Bunerwal'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Butyal'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Chakesar'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Damorai'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Dandai'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Dihrai'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Kurmang'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Kuz Kana'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Lilowani'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Maira'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Mala Khel'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Opal'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Pir Abad'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Pir Khana'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Ranyal'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Sarkool'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Shah Pur'],
            ['tehsil_name' => 'Alpuri', 'uc_name' => 'Shang'],
            ['tehsil_name' => 'Allai', 'uc_name' => 'Banna'],
            ['tehsil_name' => 'Allai', 'uc_name' => 'Bateela'],
            ['tehsil_name' => 'Allai', 'uc_name' => 'Batkul'],
            ['tehsil_name' => 'Allai', 'uc_name' => 'Biari'],
            ['tehsil_name' => 'Allai', 'uc_name' => 'Jambera'],
            ['tehsil_name' => 'Allai', 'uc_name' => 'Pashto'],
            ['tehsil_name' => 'Allai', 'uc_name' => 'Rashang'],
            ['tehsil_name' => 'Allai', 'uc_name' => 'Sakargah'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Ajmera'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Banian'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Batagram'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Batamori'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Gijbroi'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Kuza Banda'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Paimal Sharif'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Peshora'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Rajdahri'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Shumlai'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Thakot'],
            ['tehsil_name' => 'Battagram', 'uc_name' => 'Trand'],
            ['tehsil_name' => 'Ghazi', 'uc_name' => 'Baitgali'],
            ['tehsil_name' => 'Ghazi', 'uc_name' => 'Ghazi'],
            ['tehsil_name' => 'Ghazi', 'uc_name' => 'Kothera'],
            ['tehsil_name' => 'Ghazi', 'uc_name' => 'Khairbara Halmet'],
            ['tehsil_name' => 'Ghazi', 'uc_name' => 'Kundi'],
            ['tehsil_name' => 'Ghazi', 'uc_name' => 'Nara Amazai'],
            ['tehsil_name' => 'Ghazi', 'uc_name' => 'Qazipur'],
            ['tehsil_name' => 'Ghazi', 'uc_name' => 'Seri Kot'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Ali Khan'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Bagra'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Bakka'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Bandi Sher Khan'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Barkot'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Beer'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Breela'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Darwesh'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Dhenda'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Dingi'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Haripur Central'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Hattar'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Jabri'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Jatti Pind'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Khalabat'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Khanpur.'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Kholian Bala'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Kot Najeebullah'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Ladarmang'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Mankari'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Maqsood'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Muslimabad'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Najifpur'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Haripur North'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Haripur South'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Pandak'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Panian'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Pind Hasham Khan'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Pind Kamal Khan'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Rehana'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Serai Niamat Khan'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Serai Saleh'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Sikandarpur'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Tarbela'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Tofkian'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Bherrary'],
            ['tehsil_name' => 'Haripur', 'uc_name' => 'Kalinjar'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Ama Khel'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Dabara'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Gara Baloch'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Gomal'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Gul Imam'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Jattatar'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Mullazai'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Pai'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Ranwal'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Sarangzona'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Shah Alam'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Tank-I'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Tank-II'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Tatta'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Uttar'],
            ['tehsil_name' => 'Tank', 'uc_name' => 'Waraspoon'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Abakhel'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Batara'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Daggar'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Elai'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Gadezai'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Gokand'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Gulbandai'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Karapa'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Malak Pur'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Malikhel'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Pacha Kalay'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Pandair'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Soray'],
            ['tehsil_name' => 'Daggar', 'uc_name' => 'Torwarsak'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Rashaki'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Bara Banda'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Ganderi'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Kheshki Payan'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Kheshki Bala'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Dag Besud'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Jolozai'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Shakhot'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Dak Ismail Khel Chapri'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Dakhili Spin Khak (d.i.k)'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Aman Kot'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Manki Sharif'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Pahari Kati Khel'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Ziarat Kaka Sahib'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Badrashi'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Dheri Kati Khel'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Dagai'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Azakhel Bala'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Azakhel Payan'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Pir Piai'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Pabbi'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Khudrezi (khan Sher Gari)'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Akbar Pura'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Balu'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Kurvi'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Choki Mamraiz'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Taru'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Mohib Banda'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Mughalki'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Misri Banda'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Zara Miana'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Pir Sabak'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Amangarh'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Nowshera City'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Chowki Town'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Nawan Killi'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Kabal River'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Mandori'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Inzari'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Kahi'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Nizam Pur (garu)'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Khair Abad'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Mera Akora Khattak'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Adamzai'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Akora Khattak'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Jehangira'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Shaidu'],
            ['tehsil_name' => 'Nowshera', 'uc_name' => 'Jehangira-II'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Atter Shisha'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Pairan'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Sandasar'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Laber Kot'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Mansehra (rural)'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Mansehra City-I'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Mansehra City-II'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Mansehra City-III'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Mansehra City-IV'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Datta'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Behali'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Lassan Thakral'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Jaloo'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Hamsherian'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Inayat Abad'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Dhodial'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Shinkriari'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Sum Alahi Mong'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Bhogerr Mong'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Jaborri'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Sacha Kalan'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Devli Jaberr'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Hilkot'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Chater Plain'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Battal'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Icherrian'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Tanda'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Baffa Town'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Trangi Sabir Shah'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Shoukatabad'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Malik Pur'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Berkund'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Phulrraa'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Perhinna'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Swan Miara'],
            ['tehsil_name' => 'Mansehra', 'uc_name' => 'Lassan Nawab'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Akhagram'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Bandi Nigah'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Chapper'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Dislawar'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Khall'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Kotkey'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Nigah'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Pashta'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Shalfalam'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Sundal'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Toormang'],
            ['tehsil_name' => 'Wari', 'uc_name' => 'Wari'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Asbanr'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Badwan'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Balambat'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Bishgram'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Bagh Dush Khel'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Bandagai'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Chakdara'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Gall Maidan'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Haya Serai'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Khadagzai'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Khanpur'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Khungai'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Kotigram'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Kotkay'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Koto'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Lajbook'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Lal Qilla'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Manjai'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Noora Khel'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Ouch'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Rabat'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Shahi Khel'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Tazagram'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Timergara (urban)'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Zaimbdara'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Khall'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Toormang'],
            ['tehsil_name' => 'Timergara', 'uc_name' => 'Shalfalan'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Arrandu'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Asherate'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Ayun'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Broze'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Chitral-1'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Chitral-2'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Danin'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Darosh No 1'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Darosh No 2'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Karimabad'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Koh'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Lotkoh'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Shishikoh'],
            ['tehsil_name' => 'Chitral', 'uc_name' => 'Shoghore'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Bar Jalkot'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Bariyar'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Dassu'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Gabral'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Goshali'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Harban'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Karang'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Kareen'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Komila'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Kuz Jalkot'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Kuz Parwa'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Sazeen'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Seo'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Sigloo'],
            ['tehsil_name' => 'Dassu', 'uc_name' => 'Thoti'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Bar Sharyal'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Bataira Pain'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Haran'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Kaloi'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Kota Kot'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Kunshair'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Kuz Paro'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Kuz Sharyal'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Mada Khel Abad'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Peach Bola'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Shalkan Abad'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Sharakot'],
            ['tehsil_name' => 'Palas', 'uc_name' => 'Shared'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Bankhad'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Chowa Dara'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Dubair Bala'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Dubair Pain'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Dubiar Khas'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Jijal'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Kayal'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Pattan'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Ranolia'],
            ['tehsil_name' => 'Pattan', 'uc_name' => 'Sagayun'],
            ['tehsil_name' => 'NAWAGAI', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'BARA', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'JAMRUD', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'LOWER KURRAM', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'UPPER KURRAM', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'UPPER MOHMAND', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'MIRAN SHAH', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'RAZMAK', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'LADHA', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'WANA', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'JANDOLA', 'uc_name' => 'Fata'],
            ['tehsil_name' => 'Adenzai', 'uc_name' => 'Chackdara'],
            ['tehsil_name' => 'Balambat', 'uc_name' => 'Khema'],
            ['tehsil_name' => 'Balambat', 'uc_name' => 'Balambat'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Aloo'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Babozai'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Dheri'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Jamal Ghari'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Katlang 1'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Katlang 2'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Katti Ghari'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Kohi Barmol'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Kharki'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Lakpani'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Mian Khan Sangaoo'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Qasimi'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Shamozai'],
            ['tehsil_name' => 'Katlang', 'uc_name' => 'Sawal Dher'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Adina-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Adina-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Asota'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Spin Kani'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Bachai'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Sikandari'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Chak Nodeh-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Chak Nodeh-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Dagai-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Dagai-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Dagai-III'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Dobian-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Dobian-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Doulat'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Ismaila'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Ismaila South'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Ismaila Sher Ghari'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Ismaila Nazar'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Kalu Khan-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Kalu Khan-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Kalu Khan-III'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Kalu Khan-IV'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Kalu Khan-v'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Kernal Sher Kalay East'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Kernal Sher Kalay West'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Naranji-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Naranji-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Ghulaman'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Sher Dara'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Parmoli South'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Parmoli North'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Sard China'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Rukhanay'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Bazargai'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Sheikh Jana-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Sheikh Jana-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Sheikh Jana-III'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Shewa Bar Kalay'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Shwea Kuz Kalay'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Sodher'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Urmal Dheri'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Sadri'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Tarakai-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Tarakai-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Managai'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Shaheeda'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Turlandi'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Kalu Dher'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Naudeh'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Yaqoobi-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Yaqoobi-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Chak Yarhussain'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Yar Hussain East-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Yar Hussain East-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Yar Hussain East-III'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Yar Hussain West-I'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Yar Hussain West-II'],
            ['tehsil_name' => 'Razzar', 'uc_name' => 'Ziam'],
            ['tehsil_name' => 'Domel', 'uc_name' => 'Asperka Waziran'],
            ['tehsil_name' => 'Domel', 'uc_name' => 'Khander Khan Khel'],
            ['tehsil_name' => 'Domel', 'uc_name' => 'Zeraki Pirba Khel'],
            ['tehsil_name' => 'Domel', 'uc_name' => 'Aral Hathi Khel'],
            ['tehsil_name' => 'Domel', 'uc_name' => 'Domel'],
            ['tehsil_name' => 'Domel', 'uc_name' => 'Bizan Khel'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Akhoon Abad'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Andar Shehr'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Asia'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Bhana Mari'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Faqir Abad'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Gulbahar'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Gunj'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Jehangir Pura'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Kakshal-i'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Kakshal-ii'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Karim Pura'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Khalisa-i'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Khalisa-ii'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Lahori'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Mahal Therai-i'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Mahal Therai-ii'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Shaheen Muslim-1'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Shaheen Muslim-2'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Shahi Bagh'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Sheikh Junaid Abad'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Sikander Town'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Wazir Bagh'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Yakka Toot-i'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Yakka Toot-ii'],
            ['tehsil_name' => 'Peshawar Town-I', 'uc_name' =>'Yakka Toot-iii'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Budhni'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Chamkani'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Chaghar Matti'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Dug'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Garhi Sher Dad'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Gul Bela'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Haryana Payan'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Hassan Garhi No.1'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Hassan Garhi No.2'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Jogani'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Kafoor Dehri'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Kaniza'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Kankola'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Khatki'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Khazana'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Lala'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Larama'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Mathra'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Mera Kichori'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Nahaqi'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Pajjagi'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Pakha Ghulam'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Panam Dehri'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Shahi Bala'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Suliman Khel'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Takhat Abad'],
            ['tehsil_name' => 'Peshawar Town-II', 'uc_name' =>'Wadpaga'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Achini Bala'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Bazid Khel'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Deh Bahadar'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Dhari Baghbanan'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Hayat Abad-i'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Hayat Abad-ii'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Landi Arbab'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Malkandhir'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Nothia Qadeem'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Nauthia Jadeed'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Palosi'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Pawaka'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Pushtakhara Payn'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Regi'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Sarband'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Sufaid Dehri'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Tehkal Bala'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Tehkal Payan-i'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Tehkal Payan-ii'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'University Town'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Adezai'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Aza Khel'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Badabar Hurizai'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Badabar Mariamazai'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Hazar Khawani-i'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Hazar Khawani-ii'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Maryamzai'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Mashoo Gagar'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Mattani'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Mera Suri Zai Payan'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Musa Zai'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Shaheen Town'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Sheikh Muhammadi'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Sheikhan'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Sherkera'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Surizai Bala'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Surizai Payan'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Urmer Bala'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Urmer Miana'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Urmer Payan'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Suleman Khalil'],
            ['tehsil_name' => 'Peshawar Town-IV', 'uc_name' =>'Meera Khachori'],
            ['tehsil_name' => 'Peshawar Town-III', 'uc_name' =>'Nothia'],

        ];

        try {
            DB::beginTransaction();
            $unionCouncils = collect($unionCouncils)
                ->groupBy('tehsil_name')
                ->map(function ($ucNames, $tehsilName) {
                    $tehsilId = Tehsil::query()
                        ->select('id')
                        ->where('name', '=', $tehsilName)
                        ->first()
                        ->id;

                    $unionCouncils = collect($ucNames)->map(function ($ucName) use ($tehsilId) {
                        return [
                            'tehsil_id' => $tehsilId,
                            'name' => $ucName['uc_name'],
                            'created_at' => now(),
                            'updated_at' => now(),
                        ];
                    });

                    UnionCouncil::query()
                        ->insert($unionCouncils->toArray());
                });
            DB::commit();
        } catch (\Exception $exception) {
            info($exception->getMessage());
            DB::rollBack();
        }
    }
}
